### ISSUE TITLE
Display issues with newly installed Easyredmine

### ISSUE THREAD

**Issue by si-hb** [easyredmine/easyredmine#1]
See attachment. This is a brand new installation, running on a Microsoft Surface Book.

![image](https://user-images.githubusercontent.com/1800110/49084107-89d14700-f21c-11e8-9c1d-20d70a8142c5.png)

**Comment by ondra-m** [comment]
Hello,

Sorry but this repository is only for install guide. Please write to the support@easyredmine.com
